#!/bin/bash

echo "shows current folder's each dir's size (except the .. one, but including . which means total)"
#insecure version(don't use):
#( for i in * .*; do 
#  if test -d "$i" -a "$i" != ".."; then
#    du -P -s --apparent-size -- "$i" 2>/dev/null
#    #need --apparent-size! //nvmXXX ok don't use --apparent-size or --bytes or --block-size=1 because no need! Thanks to kurahaupo on #linux freenode for telling me that 'du' doesn't count links more than once (eg. due to btrfs COW)
#  fi
#done ) | sort -n -k 1

# {} is already sent as 1 arg even if it has special chars or spaces, no need to "{}" it.
# use -mindepth 1 to exclude '.' dir, '..' is already excluded!
find . -mindepth 0 -maxdepth 1 -type d -exec du -P -s --apparent-size -- {} \;  | sort -n -k 1
