#!/bin/bash

source "/swcode/swcode.bash"

rerunasroot "$@"


DNS_SERVERS_DNSMASQ_FILE="/etc/dnsmasq.d/servers.actual"
#SC2207: Prefer mapfile or read -a to split command output (or quote to avoid splitting).
# shellcheck disable=SC2207
DNS_SERVERS=( $( grep -E '^\s*server\s*=\s*[0-9]+.[0-9]+.[0-9]+.[0-9]+\s*' -- "${DNS_SERVERS_DNSMASQ_FILE}" | sed -E 's/^\s*server\s*=\s*([0-9]+.[0-9]+.[0-9]+.[0-9]+)\s*/\1/' ) )
ALLOWED_FILE="/etc/dnsmasq.d/allowed_by_script.conf"
DENIED_FILE="/etc/dnsmasq.d/denied_by_script.conf"
generic_allow_file="/etc/dnsmasq.d/allowed_by_script.hosts.lst"
generic_deny_file="/etc/dnsmasq.d/denied_by_script.hosts.lst"

base="$(basename -- "$0")"
if test "$base" == "dnswl"; then
  echo "Whitelisting mode" >&2
  APPEND_TO_FILE="$ALLOWED_FILE"
  what='allow'
elif test "$base" == "dnsbl"; then
  echo "Blacklisting mode" >&2
  APPEND_TO_FILE="$DENIED_FILE"
  what='deny'
else
  echo "!! Unknown basename '$base', aborting." >&2
  exit 4
fi

echo "Found ${#DNS_SERVERS[@]} DNS servers in file '${DNS_SERVERS_DNSMASQ_FILE}': '${DNS_SERVERS[*]}'" >&2
collected_inlist_lines=()

function is_it_in_array() {
  local search_element="$1"
  if test -z "$search_element"; then
    echo "Empty arg supplied to function '${FUNCNAME[0]}'" >&2
    exit 5
  fi
  # Initialize a flag to indicate if the element is found
  #local element_found=0

  # Iterate through the array to check if the element exists
  for element in "${collected_inlist_lines[@]}"; do
    if [[ "$element" == "$search_element" ]]; then
      #element_found=1
      return 0
      #break
    fi
  done
  return 1
}
function already_exists() {
  local expected="$1"
  local in_file="$2"
  if test "$#" -ne "2" -o -z "$1" -o -z "$2"; then
    echo "Need exactly 2 non-empty args supplied to function '${FUNCNAME[0]}', got '$#' as '$1' and '$2'" >&2
    exit 6
  fi
  #can't use this due to 'expected' may contain regex-like chars!
  #if ! grep -q "^${expected}$" -- "${APPEND_TO_FILE}" >/dev/null; then
  #  #aka non-zero exit code ie. not found
  #  return 1
  #fi

  # TODO: well, might as well store it all in memory at this point.
  # Read the file line by line
  while IFS= read -r line
  do
    if [[ "$line" == "$expected" ]]; then
      #match found
      return 0
    fi
  done < "$in_file"
  #else not found:
  return 1
}

function add_to_dnsmasq_list() {
  local host="$1"
  if test "$#" != "1"; then
    echo "!! You should pass only 1 arg to func '${FUNCNAME[0]}()', you passed $# args as '$*'" >&2
    exit 2
  fi

  for each_DNS_server in "${DNS_SERVERS[@]}"; do
    local expected
    if test "$what" == "allow"; then
      expected="server=/${host}/${each_DNS_server}"
    elif test "$what" == "deny"; then
      expected="address=/${host}/"
      #note that this works the same:
      #expected="server=/${host}/"
      #just don't add anything after the second "/", else it may even allow it, especially if it's 0.0.0.0
    else
      echo "Unhandled type '$what', aborting." >&2
    fi
    if ! already_exists "$expected" "${APPEND_TO_FILE}" >/dev/null; then
#      #aka non-zero exit code ie. does not exist
#      #so it's not already allowed/denied, so add it by showing it to stdout!
#      echo "$expected"

      # just in case the hostname is passed more than once as arg to this script, since we didn't add any to the file yet!
      if ! is_it_in_array "$expected"; then
        #aka non-zero exit code ie. not found
        #add it and return
        echo "adding host: '$host'" >&2
        collected_inlist_lines+=( "$expected" )
        #XXX: "For  historical reasons, the pattern /.google.com/ is equivalent to /google.com/ if you wish to match any subdomain of google.com but NOT google.com itself, use /*.google.com/ " - man 8 dnsmasq
        #So, if allowing something, in order to avoid allowing its subdomains as well, we add a deny rule for its subdomains! This seems to work from my testing!
        if test "$what" == "allow"; then
          #XXX: blacklist ALL subdomains, without this they'd be allowed as well!
          #"using double quotes around the string in Bash prevents pathname expansion (globbing)." - chatgpt-4o
          local expected_subdomain_blacklist="address=/*.${host}/"
          if ! already_exists "$expected_subdomain_blacklist" "${APPEND_TO_FILE}"; then
            if ! is_it_in_array "$expected_subdomain_blacklist"; then
              collected_inlist_lines+=( "$expected_subdomain_blacklist" )
            fi
          fi
        fi
      else
        echo "duplicate host arg: '$host'" >&2
      fi
    else
      echo "host already in file: '$host'" >&2
    fi
    if test "$what" == "deny"; then
      #no need to do it for each DNS server, because for 'deny' it doesn't depend on them!
      #echo "foo" >&2
      break
    fi
  done
}

#so when I wanna re-run dnswl/dnsbl on all hosts because I've changed something in code, I can do it by deleting the .conf files first and use these generic lists files as source instead, like: # dnswl `cat allowed_by_script.hosts.lst`
function add_to_generic_list() {
  local host="$1"
  if test -z "$host"; then
    echo "Should pass 1 arg to function '${FUNCNAME[0]}'" >&2
    exit 7
  fi
  if test "$what" == "allow"; then
    #XXX: can't use grep here due to '.' in hostname would match any char! and don't wanna escape it.
    #if ! grep -q -- "^${host}$" "$generic_allow_file" 2>/dev/null; then
    if ! already_exists "$host" "$generic_allow_file"; then
      echo "$host" >> "$generic_allow_file"
    fi
  elif test "$what" == "deny"; then
    #if ! grep -q -- "^${host}$" "$generic_deny_file" 2>/dev/null; then
    if ! already_exists "$host" "$generic_deny_file"; then
      echo "$host" >> "$generic_deny_file"
    fi
  else
    echo "Unexpected '$what', aborting." >&2
    exit 8
  fi
}

if test "$#" == "0"; then
  echo "!! You should pass hostname(s) as arg(s)" >&2
  exit 3
fi

if ! test -f "${APPEND_TO_FILE}"; then
  #first line here creates/overwrites the file.
  echo "# Autogenerated by '$0' aka '$(realpath -- "$0")', DO NOT EDIT, just run \`'$0' hostname\`" > "${APPEND_TO_FILE}"
  { #each of these must end in ";"
    echo "# for use by dnsmasq, this is file '${APPEND_TO_FILE}'";
    echo "#";
    echo "# Beware that having a hostname here means dnsmasq will $what all its subdomains too!";
    echo "# Also having a hostname in both allow and in deny lists will make it be allowed(and its subdomains too, unless specific subdomains are only in deny list!)!";
    echo "# actually working around for the above via "For  historical reasons, the pattern /.google.com/ is equivalent to /google.com/ if you wish to match any subdomain of google.com but NOT google.com itself, use /*.google.com/ " - man 8 dnsmasq";
    echo "# so if you see \`address=/*.google.com/\` it means it's blocking subdomains, unless they're specifically whitelisted!";
    echo "#";
  } >> "$APPEND_TO_FILE"
fi

#for tests:
#add_to_dnsmasq_allow_list blah "bla bla"
for each in "$@"; do
  add_to_dnsmasq_list "$each"
  add_to_generic_list "$each"
done

if test "${#collected_inlist_lines[@]}" -gt 0; then
  #add all changes at once!
  #TODO: ensure it's locked so no two $0 can concurrently append here and make a racy mess!
  echo "${collected_inlist_lines[@]}" | tr ' ' '\n' | tee -a "$APPEND_TO_FILE"
fi

echo "Done, file '$APPEND_TO_FILE' was updated! Now restarting dnsmasq to effectivate changes:"
rc-service dnsmasq restart
#note: reload won't do! needs to be 'restart'

