#!/usr/bin/env -S PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:${PATH}" bash

function foo() {
  local base="$(basename "$0")"
#  if test "$base" == "rustdoc"; then
    #echo "$# $0 $*" >> /tmp/foo.log
#  fi
  if test "$(id -n -u)" == "user"; then
    "/home/user/.cargo/bin/$base" "$@"
  else
    "/usr/bin/$base" "$@"
  fi
}

foo "$@"
